services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=cQM1j1id7hTqR8MXShZwQbsmeY18rBAn
      - DJANGO_ALLOWED_HOSTS=cloud.tecnogueto.com.br
      - SQL_DATABASE=postgres
      - SQL_USER=tecnogueto
      - SQL_PASSWORD=80b4d857d2cfec7f1289
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=tecnogueto
      - POSTGRES_PASSWORD=80b4d857d2cfec7f1289
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: