# Generated by Django 5.1.4 on 2024-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0002_alter_course_image_alter_course_mini_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
