# Generated by Django 5.1.4 on 2024-12-24 09:39

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0003_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "300x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="instructors/"),
        ),
    ]
